---

name: ignored
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:                            # Packages installed from PyPI
      - lets-plot==3.2.0rc1
#      - pypng                      # will be installed by lets-plot dependencies
#      - palettable
      - pillow
      - scikit-datasets
      - geopandas
      - requests
#      - ipywidgets
      - sklearn
      - cartopy
      - rasterio
      - statsmodels                 # for 'residual plot'
